all: run clean
	@echo 'Done'

test:
	@echo 'this should not be seen' > /dev/null 2>&1

clean:
	@rm -f *.test

run:
	@echo "This give different results than just running it from a shell"
	@echo "For sanity sake, just run ./test.sh"
	#@./test.sh
